config/routes.rb
Rails.application.routes.draw do

  get 'contact_us/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :welcome, only: [:index], :path => "home"

  resources :creatives, only: [:index , :show]

  resources :articles, only: [:index, :show], :path => "news"

  resources :contacts

  root 'welcome#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, :text, :author, :preview_text, presence: true
  has_one_attached :article_image
end

app/models/banner.rb
class Banner < ApplicationRecord
	validates :title, :text, :link, presence: true
	has_one_attached :banner_image
end

app/models/contact.rb
class Contact < ActiveRecord::Base

  validates :name,
            presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }

  validates :message, :presence => true
  
end

app/models/creative.rb
class Creative < ApplicationRecord
  validates :name, :description, :industry, :preview_text, presence: true
  has_one_attached :artist_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @articles = Article.new
  end

  def create
    @articles = Article.new
    if @article.save
      redirect_to @article
    end
  end

  def show
    @article = Article.find(params[:id])
    @articles = Article.all.limit(3).order("id DESC").all
  end


  def destroy
    @creative = Creative.find(params[:id])
    @creative.destroy
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def create
    begin
      @contact = Contact.new(contact_params)

      if @contact.valid?
      ApplicationMailer.new_message(@contact).deliver
      @contact.save
      redirect_to root_path, notice: "Your messages has been sent."
      else
        flash[:alert] = "An error occurred while delivering this message."
        render :new
      end
    end
  end

  protected

    def contacts
      Contact.all
    end

    def contact
      @_contact ||= Contact.find(params[:id])
    end

    def contact_name
      contact.name
    end

    def contact_params
      params.require(:contact).permit!
    end

end

app/controllers/creatives_controller.rb
class CreativesController < ApplicationController
  def index
    @creatives = Creative.all
  end

  def new
    @creatives = Creative.new
  end

  def create
    @creatives = Creative.new
    if @creative.save
      redirect_to @creative
    end
  end

  def show
    @creative = Creative.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @articles = Article.all.limit(3).order("id DESC").all
    @creatives = Creative.all.limit(3).all
    @banners = Banner.all.limit(3).order("id DESC").all    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/creatives_helper.rb
module CreativesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_analytics.html.slim
- if Rails.env.production?
  javascript:
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-165929295-1', 'auto');
      ga('send', 'pageview');

app/views/articles/index.html.slim
= stylesheet_link_tag 'articles_index', media: 'all', 'data-turbolinks-track': 'reload'


div class="headers" Up To The Minute
.articles
  - @articles.each do |article|
    - if article.article_image.present?
      div class="articles__article-card" 
        div = image_tag (article.article_image), :class=>"articles__article-card__top"
          span class="articles__article-card__top__article-cat letter-spacing" NEWS
        div class="articles__article-card__bottom"
          div class="articles__article-card__bottom__date-title"
            time class="articles__article-card__bottom__date-title__date letter-spacing" yoyyiyp 13th
          h2 class="articles__article-card__bottom__date-title__title" = article.title
          = link_to "Read More", article_path(article), class:"btn btn-primary"

/ = image_tag (article.article_image), :class => "articles__article-card__top"
/ = image_tag (@article.article_image), :class => "d-block, w-100"


footer
    div class="main-content"
      div class="left box"
        div class="content"
          p Music, People, Lifestyle and Future Creatives
      div class="center box"
        div class="social"
          a href="https://twitter.com/Argocreatives" class="social_links"
            div class="fab fa-twitter"
          a href="#"class="social_links"
            div class="fab fa-facebook-f"
          a href="https://www.instagram.com/Argocreatives/"class="social_links"
            div class="fab fa-instagram"
          a href ="" class="social_links"
            div class="fab fa-spotify"

app/views/articles/show.html.slim
= stylesheet_link_tag 'article_show', media: 'all', 'data-turbolinks-track': 'reload'

= content_for :head do
  meta content="summary" name="twitter:card" 
  meta content="#{request.original_url}" property="og:url" 
  meta content="#{@article.title}" property="og:title" 
  meta content="#{@article.preview_text}" property="og:description" 
  meta content="#{rails_blob_url @article.article_image}" property="og:image"
  

#carouselExampleIndicators.carousel.slide data-ride="carousel" 
  .carousel-inner
    .carousel-item.active
      = image_tag (@article.article_image), :class => "d-block, w-100"
      .carousel-caption.d-none.d-md-block
        h1 = @article.title

.news-section
  p = @article.text

.h5 Share on socials
.center_share
  a href ="https://twitter.com/intent/tweet?text= - #{request.original_url}" class="share_twitter a js-social-share.twitter" target="_blank"
    div class="fab fa-twitter"
  a href ="https://www.facebook.com/sharer/sharer.php?u=#{@article.title} - #{request.original_url}" class="share_facebook a js-social-share.twitter" target="_blank"
    div class="fab fa-facebook-f"

.h3 More News

.card-group
 - @articles.each do |article|
    - if article.article_image.present?
    .card
      div = image_tag (article.article_image), :class=>".card-img-top"
      .card-body
        h5.card-title = article.title
        = link_to "Read More", article_path(article), class:"btn btn-primary"


footer
    div class="main-content"
      div class="left box"
        div class="content"
          p Music, People, Lifestyle and Future Creatives
      div class="center box"
        div class="social"
          a href="https://twitter.com/Argocreatives" class="social_links"
            div class="fab fa-twitter"
          a href="#"class="social_links"
            div class="fab fa-facebook-f"
          a href="https://www.instagram.com/Argocreatives/"class="social_links"
            div class="fab fa-instagram"
          a href ="" class="social_links"
            div class="fab fa-spotify"

app/views/contacts/new.html.slim
= stylesheet_link_tag 'contact_us', media: 'all', 'data-turbolinks-track': 'reload'

.contact_us_top 
  h2.w3-wide CONTACT
  p Send us a message here:
= form_for Contact.new do |f|
 
  = f.text_field :name, placeholder: 'Name', type: 'text', class:'name'

  = f.text_field :email, placeholder: 'Email', class:'email'
  = f.text_field :phone, placeholder: 'Phone', class:'phone'
  = f.text_area :message, as: :text, placeholder: 'Message', class:'message'

  = f.submit 'Send message'

div class="center box"
  div class="social"
    a href="https://twitter.com/Argocreatives" class="social_links"
      div class="fab fa-twitter"
    a href="#"class="social_links"
      div class="fab fa-facebook-f"
    a href="https://www.instagram.com/Argocreatives/"class="social_links"
      div class="fab fa-instagram"
    a href ="" class="social_links"
      div class="fab fa-spotify"

app/views/creatives/index.html.slim
= stylesheet_link_tag 'articles_index', media: 'all', 'data-turbolinks-track': 'reload'


div class="headers" Creatives
.articles
  - @creatives.each do |creative|
      div class="articles__article-card" 
        div = image_tag (creative.artist_image), :class=>"articles__article-card__top"
          span class="articles__article-card__top__article-cat letter-spacing" = creative.industry
        div class="articles__article-card__bottom"
          div class="articles__article-card__bottom__date-title"
            time class="articles__article-card__bottom__date-title__date letter-spacing" = creative.preview_text
          h2 class="articles__article-card__bottom__date-title__title" = creative.name
          = link_to "View Creative", creative_path(creative), class:"btn btn-primary"


footer
    div class="main-content"
      div class="left box"
        div class="content"
          p Music, People, Lifestyle and Future Creatives
      div class="center box"
        div class="social"
          a href="https://twitter.com/Argocreatives" class="social_links"
            div class="fab fa-twitter"
          a href="#"class="social_links"
            div class="fab fa-facebook-f"
          a href="https://www.instagram.com/Argocreatives/"class="social_links"
            div class="fab fa-instagram"
          a href ="" class="social_links"
            div class="fab fa-spotify"

app/views/creatives/show.html.slim
= stylesheet_link_tag 'article_show', media: 'all', 'data-turbolinks-track': 'reload'

= content_for :head do
  meta content="summary" name="twitter:card" 
  meta content="#{request.original_url}" property="og:url" 
  meta content="#{@creative.name}" property="og:title" 
  meta content="#{@creative.preview_text}" property="og:description" 
  meta content="#{rails_blob_url @creative.artist_image}" property="og:image"

#carouselExampleIndicators.carousel.slide data-ride="carousel" 
  .carousel-inner
    .carousel-item.active
      = image_tag (@creative.artist_image), :class => "d-block, w-100" 
      .carousel-caption.d-none.d-md-block
        h1 = @creative.name

.news-section
  p = @creative.description
  
.center_share_artists
  - if @creative.facebook.present?
    .btn-social_artist
      i.fa.fa-facebook-official aria-hidden="true"
        a class="a.js-social-share.facebook" href=("https://www.facebook.com/#{@creative.facebook}") target="_blank" 
  - if @creative.twitter.present?       
    .btn-social_artist
      i.fa.fa-twitter aria-hidden="true"
        a class="a.js-social-share.twitter" href=("https://twitter.com/#{@creative.twitter}") target="_blank" 
  - if @creative.instagram.present?        
    .btn-social_artist
      i.fa.fa-instagram aria-hidden="true"
        a class="a.js-social-share.twitter" href=("https://instagram.com/#{@creative.instagram}") target="_blank" 
  - if @creative.youtube.present?       
    .btn-social_artist
      i.fa.fa-youtube aria-hidden="true"
        a class="a.js-social-share.twitter" href=("https://youtube.com/#{@creative.youtube}") target="_blank" 
  - if @creative.spotify.present?        
    .btn-social_artist
      i.fa.fa-spotify aria-hidden="true"
        a class="a.js-social-share.twitter" href=("https://spotify.com/#{@creative.spotify}") target="_blank" 
  - if @creative.soundcoud.present?       
    .btn-social_artist
      i.fa.fa-soundcloud aria-hidden="true"
        a class="a.js-social-share.twitter" href=("https://soundcloud.com/#{@creative.soundcoud}") target="_blank" 
  - if @creative.apple_music.present?     
    .btn-social_artist
      i.fa.fa-apple aria-hidden="true"
        a class="a.js-social-share.twitter" href=("https://itunes.apple.com/za/artist/#{@creative.apple_music}") target="_blank"

.h5 Share on socials
.center_share
  a href ="https://twitter.com/intent/tweet?text=#{@creative.name} - #{request.original_url}" class="share_twitter a js-social-share.twitter" target="_blank"
    div class="fab fa-twitter"
  a href ="https://www.facebook.com/sharer/sharer.php?u=#{@creative.name} - #{request.original_url}" class="share_facebook a js-social-share.twitter" target="_blank"
    div class="fab fa-facebook-f"


/ .h3 More about creative

/ .card-group
/   .card
/     img.card-img-top alt="..." src="https://enfntsterribles.com/wp-content/uploads/2018/08/enfntsterribles-music-travis-scott-1-2-1-e1533131706890-1000x400.jpg" 
/     .card-body
/       h5.card-title Check
/       p.card-text This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.
/       p.card-text
/         small.text-muted Last updated 3 mins ago



footer
    div class="main-content"
      div class="left box"
        div class="content"
          p Music, People, Lifestyle and Future Creatives
      div class="center box"
        div class="social"
          a href="https://twitter.com/Argocreatives" class="social_links"
            div class="fab fa-twitter"
          a href="#"class="social_links"
            div class="fab fa-facebook-f"
          a href="https://www.instagram.com/Argocreatives/"class="social_links"
            div class="fab fa-instagram"
          a href ="" class="social_links"
            div class="fab fa-spotify"

app/views/layouts/application.html.slim
doctype html
html
  head
    title Argocreatives
    = content_for :head
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = render "analytics"

    meta name="viewport" content="width=device-width, initial-scale=1.0;"

    / meta content=("<%= @article.title %>") property="og:title" 
    / meta content="article" property="og:type" 
    / meta content=("<%= article_url(@article) %>") property="og:url" 
    / meta content=("<%= @article.body %>") property="og:description" 
    / meta content=("<%= absolute_image_url(img.attachment.url) %>") property="og:image" 
    / meta content="12345678" property="fb:app_id" 
    / meta content=("<%= @article.title %>") name="twitter:card" 
    / meta content="@mytwitter" name="twitter:site" 




    link href="https://fonts.googleapis.com/css2?family=Ubuntu&display=swap" rel="stylesheet"

    link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"

    link rel="icon" href="https://res.cloudinary.com/argocreatives/image/upload/v1596243958/White%20labels/Argo_Face_Logo_Twitter_2_nzkvzd.jpg"

    script src="https://kit.fontawesome.com/157a5204f8.js" crossorigin="anonymous"

    script crossorigin="anonymous" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" src="https://code.jquery.com/jquery-3.5.1.slim.min.js" 

    script crossorigin="anonymous" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" 

    script crossorigin="anonymous" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" 


    body

      / nav.navbar.navbar-expand-lg.navbar-light.bk-light
      /   div
      /     a.navbar-brand href="#"  Navbaryouyuy
      /     button.navbar-toggler aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarNavAltMarkup" data-toggle="collapse" type="button" 
      /       span.navbar-toggler-icon
      /     #navbarNavAltMarkup.collapse.navbar-collapse
      /       .navbar-nav
      /         a.nav-item.nav-link href="#"  Features
      /         a.nav-item.nav-link href="#"  Pricing
      /         a.nav-item.nav-link.disabled href="#"  Disabled
      nav class="main-nav"
        div class="logo"
          a.h4 href="/" ARGO 
        ul class="nav-links"
          li class="nav-link" = link_to'Up To The Minute', articles_path
          li class="nav-link" = link_to 'Creatives', creatives_path
          li class="nav-link" = link_to 'Contact Us', new_contact_path
        a class="burger"
          div class="line1"
          div class="line2"
          div class="line3"

    //footer
      div class="main-content"
        div class="left box"
          h2 About us
          div class="content"
            p Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nesciunt quos eos quod, dolores aperiam nulla tempora incidunt id ullam iure quis reprehenderit totam, laboriosam at! Ab impedit magni voluptatem harum!
        div class="center box"
          div class="social"
            a href="https://twitter.com/Argocreatives" class="social_links"
              div class="fab fa-twitter"
            a href="#"class="social_links"
              div class="fab fa-facebook-f"
            a href="https://www.instagram.com/Argocreatives/"class="social_links"
              div class="fab fa-instagram"
            a href ="" class="social_links"
              div class="fab fa-spotify"


= yield

javascript:
  const navSlide = () => {
    const burger = document.querySelector(".burger");
    const nav = document.querySelector(".nav-links");
    const navLinks = document.querySelectorAll(".nav-link");

    burger.addEventListener("click", () => {
      nav.classList.toggle("nav-active");
    navLinks.forEach((link, application) => {
      link.style.animation = `navLinkFade 0.10s ease forwards ${application / 7 + 0.25}s`;
    });
    });


  };
  navSlide();

  window.dataLayer = window.dataLayer || [];
  function gtag() {
    dataLayer.push(arguments);
  }
  gtag("js", new Date());

  gtag("config", "UA-165929295-1");

app/views/welcome/index.html.slim
= stylesheet_link_tag 'welcome', media: 'all', 'data-turbolinks-track': 'reload'

#carouselExampleIndicators.carousel.slide data-ride="carousel" 
  ol.carousel-indicators
    li.active data-slide-to="0" data-target="#carouselExampleIndicators" 
    li data-slide-to="1" data-target="#carouselExampleIndicators" 
    li data-slide-to="2" data-target="#carouselExampleIndicators" 
  .carousel-inner
    .carousel-item.active
      img.d-block.w-100 alt=("First slide") src="https://enfntsterribles.com/wp-content/uploads/2018/08/enfntsterribles-music-travis-scott-1-2-1-e1533131706890-1000x400.jpg" 
      .carousel-caption.d-none.d-md-block
        h3 uuou  out
        a.h1 href="/news/2" Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam blanditiis ea quas necessitatibus esse, ul
    .carousel-item
      img.d-block.w-100 alt=("Second slide") src="https://artmarketmag.com/wp-content/uploads/2019/11/PSX_20170216_010838-1000x400.jpg"
      .carousel-caption.d-none.d-md-block
        h5 uut uot uot 
        a.h1 href="/news/3" Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam blanditiis ea quas necessitatibus esse, ul
    .carousel-item
      img.d-block.w-100 alt=("Third slide") src="https://enfntsterribles.com/wp-content/uploads/2018/08/enfntsterribles-music-travis-scott-1-2-1-e1533131706890-1000x400.jpg" 
      .carousel-caption.d-none.d-md-block
        h5 outoutou o8tuot
        a.h1 href="/news/4" Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam blanditiis ea quas necessitatibus esse, ul
  a.carousel-control-prev data-slide="prev" href="#carouselExampleIndicators" role="button" 
    span.carousel-control-prev-icon aria-hidden="true" 
    span.sr-only Previous
  a.carousel-control-next data-slide="next" href="#carouselExampleIndicators" role="button" 
    span.carousel-control-next-icon aria-hidden="true" 
    span.sr-only Next

/ #carouselExampleIndicators.carousel.slide data-ride="carousel" 
/   ol.carousel-indicators
/     li.active data-slide-to="0" data-target="#carouselExampleIndicators" 
/     li data-slide-to="1" data-target="#carouselExampleIndicators" 
/     li data-slide-to="2" data-target="#carouselExampleIndicators" 
/   .carousel-inner
/    - @banners.each do |banner|
/     - if banner.banner_image.present?
/     .carousel-item.active
/       div class="d-block" = image_tag (banner.banner_image), :class=>"w-100"
/       .carousel-caption.d-none.d-md-block
/         h3 uuou  out
/         a.h1 href="/news/2" Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam blanditiis ea quas necessitatibus esse, ul
/     .carousel-item
/       div class="d-block" = image_tag (banner.banner_image), :class=>"w-100"
/       .carousel-caption.d-none.d-md-block
/         h5 uut uot uot 
/         a.h1 href="/news/3" Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam blanditiis ea quas necessitatibus esse, ul
/     .carousel-item
/       div class="d-block" = image_tag (banner.banner_image), :class=>"w-100"
/       .carousel-caption.d-none.d-md-block
/         h5 uut uot uot 
/         a.h1 href="/news/3" Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam blanditiis ea quas necessitatibus esse, ul
/   a.carousel-control-prev data-slide="prev" href="#carouselExampleIndicators" role="button" 
/     span.carousel-control-prev-icon aria-hidden="true" 
/     span.sr-only Previous
/   a.carousel-control-next data-slide="next" href="#carouselExampleIndicators" role="button" 
/     span.carousel-control-next-icon aria-hidden="true" 
/     span.sr-only Next

// Last article
/ #carouselExampleIndicators.carousel.slide data-ride="carousel" 
/   ol.carousel-indicators
/     li.active data-slide-to="0" data-target="#carouselExampleIndicators" 
/     li data-slide-to="1" data-target="#carouselExampleIndicators" 
/     li data-slide-to="2" data-target="#carouselExampleIndicators" 
/   .carousel-inner
/    - @banners.each do |banner|
/     - if banner.banner_image.present?
/       .carousel-item.carousel-item.active
/       .carousel-item
/         div class="d-block" = image_tag (banner.banner_image), :class=>"w-100"
/         .carousel-caption.d-none.d-md-block
/           h3 uuou  out
/           a.h1 href="/news/2" Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam blanditiis ea quas necessitatibus esse, ul




.div_flex 
  div class="headers_top" Up To The Minute
  a class="view_more_articles" href="/news" View All>
.articles
  - @articles.each do |article|
    - if article.article_image.present?
      div class="articles__article-card" 
        div = image_tag (article.article_image), :class=>"articles__article-card__top"
          span class="articles__article-card__top__article-cat letter-spacing" NEWS
        div class="articles__article-card__bottom"
          div class="articles__article-card__bottom__date-title"
            time class="articles__article-card__bottom__date-title__date letter-spacing" yoyyiyp 13th
          h2 class="articles__article-card__bottom__date-title__title" = article.title
          = link_to "Read More", article_path(article), class:"btn btn-primary"


.back
  .div_flex 
    div class="headers" Creatives
    a class="view_more" href="/creatives" View All>
  .articles_artist
    - @creatives.each do |creative|
      - if creative.artist_image.present?
      div class="articles_artist_article-card"
        a href="/creatives/#{creative.id}" 
          div = image_tag (creative.artist_image), :class=>"articles_artist_article-card__top"
            span class="articles_artist_article-card__top__article-cat letter-spacing" = creative.industry
          div class="articles__article-card__bottom"
            div class="articles__article-card__bottom__date-title"
              time class="articles__article-card__bottom__date-title__date letter-spacing" Creative
            h2 class="articles__article-card__bottom__date-title__title" = creative.name

     

footer
  div class="main-content"
    div class="left box"
      div class="content"
        p Music, People, Lifestyle and Future Creatives
    div class="center box"
      div class="social"
        a href="https://twitter.com/Argocreatives" class="social_links"
          div class="fab fa-twitter"
        a href="#"class="social_links"
          div class="fab fa-facebook-f"
        a href="https://www.instagram.com/Argocreatives/"class="social_links"
          div class="fab fa-instagram"
        a href ="" class="social_links"
          div class="fab fa-spotify"